require clutter.inc
require clutter-git.inc

DEFAULT_PREFERENCE = "1"

DEPENDS = "${STDDEPENDS} ${STDDEPENDS_EGL}"
RDEPENDS = "${STDRDEPENDS} ${STDRDEPENDS_EGL}"
CONFLICTS += "clutter-1.10-x11"

EXTRA_OECONF = "${BASE_CONF} ${BASE_CONF_EGL}"



