require clutter-1.12.inc
require clutter-1.12-git.inc

PR = "${INCPR}.0"

DEPENDS = "${STDDEPENDS} ${STDDEPENDS_GLX}"
RDEPENDS = "${STDRDEPENDS} ${STDRDEPENDS_GLX}"

EXTRA_OECONF = "${BASE_CONF} ${BASE_CONF_GLX}"
